name: ai-news-analyst
services:
- name: web
  source_dir: /
  github:
    repo: your-username/ai-news-analyst
    branch: main
  run_command: python run_backend.py & python serve_frontend.py & wait
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8002
  health_check:
    http_path: /
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_MODEL
    value: gpt-4o-mini
    scope: RUN_TIME
  - key: DAILY_TOKEN_LIMIT
    value: "5000"
    scope: RUN_TIME
  - key: VECTOR_DB_PATH
    value: /app/data/vector_db
    scope: RUN_TIME
